#ifndef IRIS_PARAMS_H
#define IRIS_PARAMS_H

/* Generated by 01_train_iris.py.
 * Input order: sepal length, sepal width, petal length, petal width.
 */
static const float IRIS_MEAN[4] = {
    5.841666698f, 3.048333406f, 3.769999981f, 1.205000043f
};

static const float IRIS_SCALE[4] = {
    0.837414980f, 0.446651131f, 1.761135936f, 0.759478986f
};

#endif /* IRIS_PARAMS_H */
