"""Train a small Iris classifier and export a float32 TFLite model.

Outputs:
  iris_model.tflite  - import this into STM32CubeMX X-CUBE-AI
  iris_model.keras   - Keras backup model
  iris_params.h      - normalization constants used by the STM32 code
  iris_test.csv      - held-out validation data for serial testing
"""

from __future__ import annotations

import csv
import os
import random
from pathlib import Path

import numpy as np
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

SEED = 42
OUT_DIR = Path(__file__).resolve().parent

os.environ.setdefault("PYTHONHASHSEED", str(SEED))
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

iris = load_iris()
X = iris.data.astype(np.float32)
y = iris.target.astype(np.int32)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=SEED,
    stratify=y,
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train).astype(np.float32)
X_test_scaled = scaler.transform(X_test).astype(np.float32)

model = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(4,), name="iris_input"),
        tf.keras.layers.Dense(8, activation="relu", name="dense_1"),
        tf.keras.layers.Dense(8, activation="relu", name="dense_2"),
        tf.keras.layers.Dense(3, activation="softmax", name="iris_output"),
    ],
    name="iris_classifier",
)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

model.fit(
    X_train_scaled,
    y_train,
    epochs=300,
    batch_size=16,
    verbose=0,
    shuffle=True,
)

loss, accuracy = model.evaluate(X_test_scaled, y_test, verbose=0)
print(f"PC test accuracy: {accuracy * 100:.2f}%  loss={loss:.6f}")

keras_path = OUT_DIR / "iris_model.keras"
model.save(keras_path)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
tflite_path = OUT_DIR / "iris_model.tflite"
tflite_path.write_bytes(tflite_model)

mean = scaler.mean_.astype(np.float32)
scale = scaler.scale_.astype(np.float32)

header = f"""#ifndef IRIS_PARAMS_H\n#define IRIS_PARAMS_H\n\n/* Generated by 01_train_iris.py.\n * Input order: sepal length, sepal width, petal length, petal width.\n */\nstatic const float IRIS_MEAN[4] = {{\n    {mean[0]:.9f}f, {mean[1]:.9f}f, {mean[2]:.9f}f, {mean[3]:.9f}f\n}};\n\nstatic const float IRIS_SCALE[4] = {{\n    {scale[0]:.9f}f, {scale[1]:.9f}f, {scale[2]:.9f}f, {scale[3]:.9f}f\n}};\n\n#endif /* IRIS_PARAMS_H */\n"""
(OUT_DIR / "iris_params.h").write_text(header, encoding="utf-8")

with (OUT_DIR / "iris_test.csv").open("w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(
        ["label", "sepal_length", "sepal_width", "petal_length", "petal_width"]
    )
    for row, label in zip(X_test, y_test):
        writer.writerow([int(label), *[f"{float(v):.4f}" for v in row]])

print(f"Created: {tflite_path}")
print(f"Created: {OUT_DIR / 'iris_params.h'}")
print(f"Created: {OUT_DIR / 'iris_test.csv'}")
print("Class mapping: 0=setosa, 1=versicolor, 2=virginica")
print("Example serial command: P,5.1,3.5,1.4,0.2")

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=["sepal_length","sepal_width","petal_length","petal_width"]
)

df["label"] = iris.target
df["class_name"] = [iris.target_names[i] for i in iris.target]

df.to_csv("iris_dataset.csv", index=False)

print("iris_dataset.csv 已生成")